# Header
menu:
  主页: /
  小技术: /categories/coding/
  小清新: /categories/life/
  总目录: /archives
  关于我: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- recent_posts
- category
- weibo
- tagcloud
- archive
- links

# Miscellaneous
favicon: /css/images/favicon.png
twitter: HKEY_C17
google_plus: '118157846818083514683'
fb_admins: sykiechencixi
fb_app_id:


# Scroll to top
go_top: true
# blogroll
links:
- name: 熊神 - xindervella
  link: http://xindervella.com/
- name: 404 page
  link: http://www.c17.co/404.html
- name: Is Fang Binxing Dead?
  link: http://isfangbinxingdead.com

# about me
about_me:
  avatar: /css/images/avatar.png
  texts:
  - <a href="mailto:c17@c17.co">Sykie Chen</a>
  - or HKEY_C17
  - 码渣 / 前医学生 / ENTP
  - 不谈中医我们还是好朋友
