# Header
menu:
  主页: /
  小技术: /categories/coding/
  小清新: /categories/life/
  总目录: /archives
  关于我: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- recent_posts
- category
- weibo
- tagcloud
- archive
- links

# Miscellaneous
favicon: /favicon.ico
twitter: HKEY_C17
google_plus: '118157846818083514683'
fb_admins: sykiechencixi
fb_app_id:


# Scroll to top
go_top: true
# blogroll
links:
- name: Yay Ka-Boom-Boom - 郭都豪
  link: http://www.lynx.im/
- name: 王雨峰同学吃了一块二向箔
  link: http://www.wangyufeng.org/
- name: 熊神 - xindervella
  link: http://xindervella.com/
- name: 南京风行数码 - 绝壁不会坑你
  link: http://www.zol.com/shop_183165/
- name: Is Fang Binxing Dead?
  link: http://isfangbinxingdead.com

# about me
about_me:
  avatar: /css/images/avatar.png
  texts:
  - <a href="http://www.devchen.com/about/">Sykie Chen</a>
  - or HKEY_C17
  - 码渣 / 前医学生
  - 微信公众号：十七的空指针


# duoshuo author key
duoshuo_info:
  data_author_key: 233

