# Header
menu:
  主页: /
  小技术: /categories/coding/
  小清新: /categories/life/
  总目录: /archives
  关于我: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- recent_posts
- category
- weibo
- links
# - tagcloud
# - archive

# Miscellaneous
favicon: /favicon.ico
twitter: HKEY_C17
google_plus: '118157846818083514683'
fb_admins: sykiechencixi
fb_app_id:


# Scroll to top
go_top: true
# blogroll
links:
- name: Yay Ka-Boom-Boom
  link: http://www.lynx.im/friends
- name: 王雨峰同学吃了一块二向箔
  link: http://www.wangyufeng.org/
- name: Anotherhome - ペロペロ
  link: https://www.anotherhome.net/link
- name: RandyPeng's Notes
  link: http://pengzhendong.cn/friends/
- name: 香蕉
  link: http://www.bananau.com/?page_id=15
- name: 燃冰非冰 - Yogi Ai
  link: http://navyblue.top/
- name: 程序员的资料库
  link: http://codecloud.net/links
- name: Android 源码下载
  link: http://www.code4apk.com/
- name: 苏苏
  link: http://sukai.me/
- name: 有趣独立技术博客导航
  link: http://iblogs.xyz/

# about me
about_me:
  avatar: /css/images/avatar.png
  texts:
  - <a href="http://www.devchen.com/about/">Sykie Chen</a>
  - or HKEY_C17
  - 码渣 / 前医学生
  - 微信公众号：<a href="http://qr.liantu.com/api.php?text=http://weixin.qq.com/r/NTsEHB7Et0PIrVp-924n">十七的空指针</a>


# duoshuo author key
duoshuo_info:
  data_author_key: 233
